import { PrismaClient } from "@prisma/client";

export async function seedPartyFormAttributes(prisma: PrismaClient) {
  // BUYERS
  await prisma.partyFormAttribute.createMany({
    data: [
      {
        name: "nome",
        type: "text",
        title: "Nome",
        placeholder: "",
        required: true,
        order: 1,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: "",
      },
      {
        name: "nacionalidade",
        type: "checkbox",
        title: "Nacionalidade",
        placeholder: "",
        required: true,
        order: 2,
        regexFormat: "",
        default: "Brasileira",
        partyFormType: "BUYERS",
        options: "Brasileira"
      },
      {
        name: "sexo",
        type: "radio",
        title: "Sexo",
        placeholder: "",
        required: true,
        order: 3,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: "Masculino,Feminino"
      },
      {
        name: "profissao",
        type: "text",
        title: "Profissão",
        placeholder: "",
        required: true,
        order: 4,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "estadoCivil",
        type: "radio",
        title: "Estado Civil",
        placeholder: "",
        required: true,
        order: 5,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: "Solteiro,Casado,Divorciado,Viúvo,Separado,União Estável"
      },
      {
        name: "rg",
        type: "text",
        title: "RG",
        placeholder: "",
        required: true,
        order: 6,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "rgEmissor",
        type: "text",
        title: "RG Emissor",
        placeholder: "SSP/SP",
        required: true,
        order: 7,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "cpf",
        type: "text",
        title: "CPF",
        placeholder: "",
        required: true,
        order: 8,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "cep",
        type: "text",
        title: "CEP",
        placeholder: "00000-000",
        required: true,
        order: 9,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "estado",
        type: "text",
        title: "Estado",
        placeholder: "",
        required: true,
        order: 10,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "cidade",
        type: "text",
        title: "Cidade",
        placeholder: "",
        required: true,
        order: 11,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "bairro",
        type: "text",
        title: "Bairro",
        placeholder: "",
        required: true,
        order: 12,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "rua",
        type: "text",
        title: "Rua",
        placeholder: "",
        required: true,
        order: 13,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "numero",
        type: "text",
        title: "Número",
        placeholder: "",
        required: true,
        order: 14,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "complemento",
        type: "text",
        title: "Complemento",
        placeholder: "",
        required: false,
        order: 15,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "dataNascimento",
        type: "date",
        title: "Data de Nascimento",
        placeholder: "",
        required: true,
        order: 16,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "nomePai",
        type: "text",
        title: "Nome completo do pai",
        placeholder: "",
        required: true,
        order: 17,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
      {
        name: "nomeMae",
        type: "text",
        title: "Nome completo da mãe",
        placeholder: "",
        required: true,
        order: 18,
        regexFormat: "",
        default: "",
        partyFormType: "BUYERS",
        options: ""
      },
    ]
  });

  //SELLERS
  await prisma.partyFormAttribute.createMany({
    data: [
      {
        name: "nome",
        type: "text",
        title: "Nome",
        placeholder: "",
        required: true,
        order: 1,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: "",
      },
      {
        name: "nacionalidade",
        type: "checkbox",
        title: "Nacionalidade",
        placeholder: "",
        required: true,
        order: 2,
        regexFormat: "",
        default: "Brasileira",
        partyFormType: "SELLERS",
        options: "Brasileira"
      },
      {
        name: "sexo",
        type: "radio",
        title: "Sexo",
        placeholder: "",
        required: true,
        order: 3,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: "Masculino,Feminino"
      },
      {
        name: "profissao",
        type: "text",
        title: "Profissão",
        placeholder: "",
        required: true,
        order: 4,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "estadoCivil",
        type: "radio",
        title: "Estado Civil",
        placeholder: "",
        required: true,
        order: 5,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: "Solteiro,Casado,Divorciado,Viúvo,Separado,União Estável"
      },
      {
        name: "rg",
        type: "text",
        title: "RG",
        placeholder: "",
        required: true,
        order: 6,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "rgEmissor",
        type: "text",
        title: "RG Emissor",
        placeholder: "SSP/SP",
        required: true,
        order: 7,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "cpf",
        type: "text",
        title: "CPF",
        placeholder: "",
        required: true,
        order: 8,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "cep",
        type: "text",
        title: "CEP",
        placeholder: "00000-000",
        required: true,
        order: 9,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "estado",
        type: "text",
        title: "Estado",
        placeholder: "",
        required: true,
        order: 10,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "cidade",
        type: "text",
        title: "Cidade",
        placeholder: "",
        required: true,
        order: 11,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "bairro",
        type: "text",
        title: "Bairro",
        placeholder: "",
        required: true,
        order: 12,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "rua",
        type: "text",
        title: "Rua",
        placeholder: "",
        required: true,
        order: 13,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "numero",
        type: "text",
        title: "Número",
        placeholder: "",
        required: true,
        order: 14,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "complemento",
        type: "text",
        title: "Complemento",
        placeholder: "",
        required: false,
        order: 15,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "dataNascimento",
        type: "date",
        title: "Data de Nascimento",
        placeholder: "",
        required: true,
        order: 16,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "nomePai",
        type: "text",
        title: "Nome completo do pai",
        placeholder: "",
        required: true,
        order: 17,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
      {
        name: "nomeMae",
        type: "text",
        title: "Nome completo da mãe",
        placeholder: "",
        required: true,
        order: 18,
        regexFormat: "",
        default: "",
        partyFormType: "SELLERS",
        options: ""
      },
    ]
  });
}
